### ISSUE TITLE
Bug running BLS depending on number of workers

### ISSUE THREAD

**Issue by joshuawallace** [waqasbhatti/astrobase#50]
Running `periodbase.bls_parallel_pfind`, I found that one of my light curves fails with the following error:

> [2018-05-07T20:32:43Z - INFO] min P: 20.378488547282885, max P: 77.59986466999999, nfreq: 562, minfreq: 0.012886620411679645, maxfreq: 0.04907135274923677
[2018-05-07T20:32:43Z - INFO] autofreq = True: using AUTOMATIC values for freq stepsize: 6.443310205839823e-05, nphasebins: 100, min transit duration: 0.02, max transit duration: 0.55
Traceback (most recent call last):
  File "generalvar_astrobase_search.py", line 234, in <module>
    main()
  File "generalvar_astrobase_search.py", line 196, in main
    bls = periodbase.bls_parallel_pfind(times,mags,errs,startp=pmin,endp=maximum_obs_length[obj],mintransitduration=.02,maxtransitduration=.55,nbestpeaks=3,sigclip=sigclipvalue,nworkers=njobs,verbose=True)
  File "/home/jwallace/astrobase_waqas/astrobase/astrobase/periodbase/kbls.py", line 600, in bls_parallel_pfind
    chunk_minfreqs = [frequencies[x*chunksize] for x in range(nworkers)]
  File "/home/jwallace/astrobase_waqas/astrobase/astrobase/periodbase/kbls.py", line 600, in <listcomp>
    chunk_minfreqs = [frequencies[x*chunksize] for x in range(nworkers)]
IndexError: index 567 is out of bounds for axis 0 with size 562

However, this seems to depend on the value of `nworkers`.  The above is with `nworkers=28`, below is with `nworkers=20` (ran succesfully)

> [2018-05-07T20:32:26Z - INFO] min P: 20.378488547282885, max P: 77.59986466999999, nfreq: 562, minfreq: 0.012886620411679645, maxfreq: 0.04907135274923677
[2018-05-07T20:32:26Z - INFO] autofreq = True: using AUTOMATIC values for freq stepsize: 6.443310205839823e-05, nphasebins: 100, min transit duration: 0.02, max transit duration: 0.55
[2018-05-07T20:32:26Z - INFO] worker 1: minfreq = 0.013, nfreqs = 29
[2018-05-07T20:32:26Z - INFO] worker 2: minfreq = 0.015, nfreqs = 29
[2018-05-07T20:32:26Z - INFO] worker 3: minfreq = 0.017, nfreqs = 29
[2018-05-07T20:32:26Z - INFO] worker 4: minfreq = 0.018, nfreqs = 29
[2018-05-07T20:32:26Z - INFO] worker 5: minfreq = 0.020, nfreqs = 29
[2018-05-07T20:32:26Z - INFO] worker 6: minfreq = 0.022, nfreqs = 29
[2018-05-07T20:32:26Z - INFO] worker 7: minfreq = 0.024, nfreqs = 29
[2018-05-07T20:32:26Z - INFO] worker 8: minfreq = 0.026, nfreqs = 29
[2018-05-07T20:32:26Z - INFO] worker 9: minfreq = 0.028, nfreqs = 29
[2018-05-07T20:32:26Z - INFO] worker 10: minfreq = 0.030, nfreqs = 29
[2018-05-07T20:32:26Z - INFO] worker 11: minfreq = 0.032, nfreqs = 29
[2018-05-07T20:32:26Z - INFO] worker 12: minfreq = 0.033, nfreqs = 29
[2018-05-07T20:32:26Z - INFO] worker 13: minfreq = 0.035, nfreqs = 29
[2018-05-07T20:32:26Z - INFO] worker 14: minfreq = 0.037, nfreqs = 29
[2018-05-07T20:32:26Z - INFO] worker 15: minfreq = 0.039, nfreqs = 29
[2018-05-07T20:32:26Z - INFO] worker 16: minfreq = 0.041, nfreqs = 29
[2018-05-07T20:32:26Z - INFO] worker 17: minfreq = 0.043, nfreqs = 29
[2018-05-07T20:32:26Z - INFO] worker 18: minfreq = 0.045, nfreqs = 29
[2018-05-07T20:32:26Z - INFO] worker 19: minfreq = 0.047, nfreqs = 29
[2018-05-07T20:32:26Z - INFO] worker 20: minfreq = 0.048, nfreqs = 11
[2018-05-07T20:32:26Z - INFO] running...
[2018-05-07T20:32:26Z - INFO] auto-cadence for mag series: 0.02043
[2018-05-07T20:32:26Z - WRN!] fit bestperiod = 1.65311 may be an alias, naively calculated bestperiod is = 2.69699

It also seems to depend on the value of min P that I give.  The above value, ~20.4 days, is fairly large for my run (the light curve only covers ~80 days total).  If I divide min P by 10, I get a successful run even with 28 workers.  Same with dividing min P by 2.

I'll send along the light curve for your reference.  For the failed run, here is my full call:

> bls = periodbase.bls_parallel_pfind(times,mags,errs,startp=20.378488547282885,endp=77.59986466999999,mintransitduration=.02,maxtransitduration=.55,nbestpeaks=3,sigclip=5.,nworkers=28,verbose=True)

**Comment by waqasbhatti** [comment]
I think 74355a63e63187ec237007a5c5cfa03e548667c0 should fix this. Let me know if it works as expected.
